// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppColors.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hsluv2rgb_cpp
Rcpp::IntegerVector hsluv2rgb_cpp(double h, double s, double l);
RcppExport SEXP _RcppColors_hsluv2rgb_cpp(SEXP hSEXP, SEXP sSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(hsluv2rgb_cpp(h, s, l));
    return rcpp_result_gen;
END_RCPP
}
// hsluv_cpp
std::string hsluv_cpp(double h, double s, double l);
RcppExport SEXP _RcppColors_hsluv_cpp(SEXP hSEXP, SEXP sSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(hsluv_cpp(h, s, l));
    return rcpp_result_gen;
END_RCPP
}
// hsluv_alpha_cpp
std::string hsluv_alpha_cpp(double h, double s, double l, double alpha);
RcppExport SEXP _RcppColors_hsluv_alpha_cpp(SEXP hSEXP, SEXP sSEXP, SEXP lSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(hsluv_alpha_cpp(h, s, l, alpha));
    return rcpp_result_gen;
END_RCPP
}
// ColorMap1
Rcpp::CharacterMatrix ColorMap1(Rcpp::ComplexMatrix Z, std::string bkgcolor, std::string nancolor, bool revr, bool revg, bool revb, const unsigned int nthreads);
RcppExport SEXP _RcppColors_ColorMap1(SEXP ZSEXP, SEXP bkgcolorSEXP, SEXP nancolorSEXP, SEXP revrSEXP, SEXP revgSEXP, SEXP revbSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::ComplexMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< std::string >::type bkgcolor(bkgcolorSEXP);
    Rcpp::traits::input_parameter< std::string >::type nancolor(nancolorSEXP);
    Rcpp::traits::input_parameter< bool >::type revr(revrSEXP);
    Rcpp::traits::input_parameter< bool >::type revg(revgSEXP);
    Rcpp::traits::input_parameter< bool >::type revb(revbSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ColorMap1(Z, bkgcolor, nancolor, revr, revg, revb, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// ColorMap2
Rcpp::CharacterMatrix ColorMap2(Rcpp::ComplexMatrix Z, std::string bkgcolor, std::string nancolor, bool revh, bool revs, bool revl, const unsigned int nthreads);
RcppExport SEXP _RcppColors_ColorMap2(SEXP ZSEXP, SEXP bkgcolorSEXP, SEXP nancolorSEXP, SEXP revhSEXP, SEXP revsSEXP, SEXP revlSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::ComplexMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< std::string >::type bkgcolor(bkgcolorSEXP);
    Rcpp::traits::input_parameter< std::string >::type nancolor(nancolorSEXP);
    Rcpp::traits::input_parameter< bool >::type revh(revhSEXP);
    Rcpp::traits::input_parameter< bool >::type revs(revsSEXP);
    Rcpp::traits::input_parameter< bool >::type revl(revlSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ColorMap2(Z, bkgcolor, nancolor, revh, revs, revl, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppColors_hsluv2rgb_cpp", (DL_FUNC) &_RcppColors_hsluv2rgb_cpp, 3},
    {"_RcppColors_hsluv_cpp", (DL_FUNC) &_RcppColors_hsluv_cpp, 3},
    {"_RcppColors_hsluv_alpha_cpp", (DL_FUNC) &_RcppColors_hsluv_alpha_cpp, 4},
    {"_RcppColors_ColorMap1", (DL_FUNC) &_RcppColors_ColorMap1, 7},
    {"_RcppColors_ColorMap2", (DL_FUNC) &_RcppColors_ColorMap2, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppColors(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
