# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hsluv2rgb_cpp <- function(h, s, l) {
    .Call(`_RcppColors_hsluv2rgb_cpp`, h, s, l)
}

hsluv_cpp <- function(h, s, l) {
    .Call(`_RcppColors_hsluv_cpp`, h, s, l)
}

hsluv_alpha_cpp <- function(h, s, l, alpha) {
    .Call(`_RcppColors_hsluv_alpha_cpp`, h, s, l, alpha)
}

