# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hsluv2rgb_cpp <- function(h, s, l) {
    .Call(`_RcppColors_hsluv2rgb_cpp`, h, s, l)
}

hsluv_cpp <- function(h, s, l) {
    .Call(`_RcppColors_hsluv_cpp`, h, s, l)
}

hsluv_alpha_cpp <- function(h, s, l, alpha) {
    .Call(`_RcppColors_hsluv_alpha_cpp`, h, s, l, alpha)
}

hsl_cpp <- function(h, s, l) {
    .Call(`_RcppColors_hsl_cpp`, h, s, l)
}

hsl_alpha_cpp <- function(h, s, l, alpha) {
    .Call(`_RcppColors_hsl_alpha_cpp`, h, s, l, alpha)
}

ColorMap1 <- function(Z, bkgcolor, nancolor, revr, revg, revb, nthreads) {
    .Call(`_RcppColors_ColorMap1`, Z, bkgcolor, nancolor, revr, revg, revb, nthreads)
}

ColorMap2 <- function(Z, bkgcolor, nancolor, revh, revs, revl, nthreads) {
    .Call(`_RcppColors_ColorMap2`, Z, bkgcolor, nancolor, revh, revs, revl, nthreads)
}

ColorMap3 <- function(Z, bkgcolor, nancolor, s, r, nthreads) {
    .Call(`_RcppColors_ColorMap3`, Z, bkgcolor, nancolor, s, r, nthreads)
}

ColorMap4 <- function(Z, bkgcolor, nancolor, revh, revs, revl, nthreads) {
    .Call(`_RcppColors_ColorMap4`, Z, bkgcolor, nancolor, revh, revs, revl, nthreads)
}

ColorMap5 <- function(Z, bkgcolor, nancolor, revh, revs, revi, nthreads) {
    .Call(`_RcppColors_ColorMap5`, Z, bkgcolor, nancolor, revh, revs, revi, nthreads)
}

ColorMap6 <- function(Z, bkgcolor, nancolor, revh, revs, revl, nthreads) {
    .Call(`_RcppColors_ColorMap6`, Z, bkgcolor, nancolor, revh, revs, revl, nthreads)
}

ColorMap7 <- function(Z, bkgcolor, nancolor, revh, revs, revv, nthreads) {
    .Call(`_RcppColors_ColorMap7`, Z, bkgcolor, nancolor, revh, revs, revv, nthreads)
}

